### ISSUE TITLE
Question - Can I show data from a database?

### ISSUE THREAD

**Issue by Martin-Andersen** [farzadso/NewsTickerPlugin#1]
Is it possible to show dynamic data from a database?

If not can you help me with installing this [Web Ticker](https://maze.digital/webticker/examples/#update) into Apex

**Comment by farzadso** [comment]
yes, it is, all you need to do is create a hidden page item (for instance `P1_NEW`), set its source to whatever you want, for example a sql query like :
`SELECT NAME FROM EMP WHERE ID = 1`
then reference this item in the Web Ticker plugin like : `&P1_NEW.`

**Comment by Martin-Andersen** [comment]
Thanks very easy if you know how to do it (-:

**Comment by farzadso** [comment]
if you have issues and you need more help, create an example on apex.oracle.com and give me credentials to login so i can help you
