### ISSUE TITLE
Version for apex 4.2

### ISSUE THREAD

**Issue by EC6RLCU** [farzadso/NewsTickerPlugin#2]
Hello Farzad 
is there still a version for Apex 4.2?
Regards Bernhard

**Comment by farzadso** [comment]
Hi there,

Have you tried it on Apex 4.2 ? The last time I tested it, there were no issues, are you running into any issues?

**Comment by EC6RLCU** [comment]
Hi,
when I try the installation I get the message "File is not a valid Application Express plug-in eport file". 
I think the export was made on a APES 5.x installation, I'am on a APEX 4.2...
regards

**Comment by farzadso** [comment]
I will create a 4.2 version for you

**Comment by EC6RLCU** [comment]
Thank's a lot:-)

**Comment by farzadso** [comment]
Hi, I added the 4.2 version in the master branch. It's called "item_type_plugin_com_jafr_news_ticker_4.2.sql". Test it out.
